FROM haskell:8.8.3

RUN apt-get update
RUN apt-get install -y liblzma-dev libbz2-dev

RUN mkdir -p /opt/prime
WORKDIR /opt/prime

RUN cabal new-update

COPY . .

RUN cabal new-install --dependencies-only

RUN cabal new-build \
  --ghc-options="-O3" \
  --ghc-options="-threaded" \
  --ghc-options="-rtsopts" \
  --ghc-options="-with-rtsopts=-N" \
  --ghc-options="-fPIC" \
  --ghc-options="-fllvm" \
  --ghc-options="-split-objs"
RUN cabal new-install

ENTRYPOINT ["prime"]
