name: Prime

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master ]

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: Cachix
      run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use static-haskell-nix
        cachix use soallpeach
    - name: Build
      run: |
        nix-build static.nix -A env | cachix push soallpeach
        nix-build static.nix
      working-directory: ./prime
      env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Assertion
      run: ldd ./result/bin/prime || true
      working-directory: ./prime
    # - name: UPX
    #   run: |
    #     nix-env -iA upx -f '<nixpkgs>'
    #     sudo mv ./result/bin/prime ./prime
    #     sudo chmod 777 ./prime
    #     upx --ultra-brute ./prime
    #   working-directory: ./prime
    - name: Binary Information
      run: file ./prime
      working-directory: ./prime
    - name: Benchmark
      run: time ./prime ./input.txt
      working-directory: ./prime
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: prime
        path: ./prime

  docker-static:
    name: Docker - Static
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --tag prime:latest
      working-directory: ./prime
    - name: Benchmark
      run: |
        mkdir data
        cp input.txt data/
        export COMMAND=$(docker inspect prime --format='{{.ContainerConfig.Entrypoint}}')
        CMD=${COMMAND:1:$((${#COMMAND} - 2))}
        time docker run --rm -v "$PWD/data/:/data/" --entrypoint="" prime:latest  sh -c "$CMD /data/input.txt > /data/result.txt"
      working-directory: ./prime

  # docker-dynamic:
  #   name: Docker - Dynamic
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build
  #     run: docker build . --file dockerfile.build --tag prime:latest
  #     working-directory: ./prime
  #   - name: Benchmark
  #     run: time docker run -v $(pwd)/input.txt:/data/input.txt prime:latest /data/input.txt > ./result.txt
  #     working-directory: ./prime
